language: csharp
# dotnet: 2.2.300
mono: none

sudo: required

dist: xenial
services:
  - docker

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1   

os:
  - linux

script:
  # install qemu for cross build
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y qemu qemu-user-static qemu-user binfmt-support
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # install dotnet core
  - curl https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 3.1.403
  - export PATH="/home/travis/.dotnet":"$PATH"
  - dotnet --info
  # build code
  - dotnet publish src/oc -o $TRAVIS_BUILD_DIR/.root/app
  # extract the oc version from the csproj
  - OC_VERSION=$(cat src/oc/oc.csproj | grep "</OrchardVersion>" | awk -F'OrchardVersion>|</' '{print $2}')
  - echo $OC_VERSION
  # build x86 version
  - docker build -t awyl/oc:x86-$OC_VERSION --build-arg IMAGE_BASE=mcr.microsoft.com/dotnet/core/aspnet:3.1.9-buster-slim .
  # copy the qemu file necessary for cross build
  - mkdir -p $TRAVIS_BUILD_DIR/.root/usr/bin
  - cp /usr/bin/qemu-arm-static $TRAVIS_BUILD_DIR/.root/usr/bin
  - docker build -t awyl/oc:arm32v7-$OC_VERSION --build-arg IMAGE_BASE=mcr.microsoft.com/dotnet/core/aspnet:3.1.9-buster-slim-arm32v7 .
  # deploy to docker hub
  - echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin;
  - docker push awyl/oc;
