language: csharp
# dotnet: 2.2.300
mono: none

sudo: required

dist: xenial
services:
  - docker

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1   

os:
  - linux

script:
  - sudo apt update
  - sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
  # - docker run --rm --privileged multiarch/qemu-user-static:register 
  - curl https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 2.2.300
  - export PATH="/home/travis/.dotnet":"$PATH"
  - dotnet --info
  - dotnet publish src/oc -o $TRAVIS_BUILD_DIR/.build/release
  # extra the oc version from the csproj
  - OC_VERSION=$(cat src/oc/oc.csproj | grep "</OrchardVersion>" | awk -F'OrchardVersion>|</' '{print $2}')
  - echo $OC_VERSION
  - pwd
  - docker build -t awyl/oc:arm32v7-$OC_VERSION --build-arg IMAGE_BASE=mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim-arm32v7 .
  - docker build -t awyl/oc:x86-$OC_VERSION --build-arg IMAGE_BASE=mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim .
  - echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin;
  - docker push awyl/oc;
